name: system

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TEXLIVE_RELEASE: 2021

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev-8 branch
  push:
    branches: [ dev-8 ]
  pull_request:
    branches: [ dev-8 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
#      fail-fast: false
      matrix:
        archetype: [book, presentation, welcome, basic-latex]
        output: [html, pdf]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  
          fetch-depth: 0
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-8.0
      - name: prepare PATH
        shell: bash
        run: |
          echo "$HOME/texlive/bin/x86_64-linux" >> $GITHUB_PATH
          echo "$HOME/texlive/bin/x86_64-darwin" >> $GITHUB_PATH
      - name: install latex
        shell: bash
        run: |
          ./scripts/ci/install-texlive
          ./archetypes/book/support/latex/ensure-deps.sh
      - shell: bash
        timeout-minutes: 15
        run: |
          scripts/system-tests/testarchetype.sh  ${{ matrix.archetype }} ${{ matrix.output }}
        
