name: unitTests

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on: [ push, pull_request ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-10
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }} .smalltalk.Unit.DocumentModel.ston
        shell: bash
        timeout-minutes: 15
